# coding: utf-8


CHANNELS = [
{'epg_id': '14135', 'index': '1', 'name': 'TVP1 HD', 'wiki_page': None},
{'epg_id': '14999', 'index': '2', 'name': 'TVP2 HD', 'wiki_page': None},
{'epg_id': '14171', 'index': '3', 'name': 'TVN HD', 'wiki_page': None},
{'epg_id': '14177', 'index': '4', 'name': 'TVN 7 HD', 'wiki_page': None},
{'epg_id': '14137', 'index': '5', 'name': 'Polsat HD', 'wiki_page': None},
{'epg_id': '14301', 'index': '6', 'name': 'TV4 HD', 'wiki_page': None},
{'epg_id': '15019', 'index': '7', 'name': 'TV Puls HD', 'wiki_page': None},
{'epg_id': '14199', 'index': '8', 'name': 'TV Puls 2 HD', 'wiki_page': None},
{'epg_id': '14185', 'index': '9', 'name': 'TTV HD', 'wiki_page': None},
{'epg_id': '14294', 'index': '10', 'name': 'Super Polsat HD', 'wiki_page': None},
{'epg_id': '14015', 'index': '11', 'name': 'TVP Polonia', 'wiki_page': None},
{'epg_id': '14173', 'index': '12', 'name': 'TV6 HD', 'wiki_page': None},
{'epg_id': '14250', 'index': '13', 'name': 'Comedy Central HD', 'wiki_page': None},
{'epg_id': '14175', 'index': '14', 'name': 'Paramount Channel HD', 'wiki_page': None},
{'epg_id': '14097', 'index': '15', 'name': 'Comedy Central Family HD', 'wiki_page': None},
{'epg_id': '14190', 'index': '16', 'name': 'TVN24 HD', 'wiki_page': None},
{'epg_id': '14014', 'index': '17', 'name': 'TVP Info HD', 'wiki_page': None},
{'epg_id': '14215', 'index': '18', 'name': 'TVP3', 'wiki_page': None},
{'epg_id': '14249', 'index': '19', 'name': 'TV Republika', 'wiki_page': None},
{'epg_id': '14323', 'index': '20', 'name': 'wPolsce 4K Ultra HD', 'wiki_page': None},
{'epg_id': '14287', 'index': '21', 'name': 'Nowa TV HD', 'wiki_page': None},
{'epg_id': '14289', 'index': '22', 'name': 'Metro TV HD', 'wiki_page': None},
{'epg_id': '14288', 'index': '23', 'name': 'WP', 'wiki_page': None},
{'epg_id': '14286', 'index': '24', 'name': 'Zoom TV', 'wiki_page': None},
{'epg_id': '14295', 'index': '25', 'name': 'Festival 4K Ultra HD', 'wiki_page': None},
{'epg_id': '14162', 'index': '26', 'name': 'Eurosport 1 HD', 'wiki_page': None},
{'epg_id': '14163', 'index': '27', 'name': 'Eurosport 2 HD', 'wiki_page': None},
{'epg_id': '14108', 'index': '28', 'name': 'TVP Sport HD', 'wiki_page': None},
{'epg_id': '14258', 'index': '29', 'name': 'TVN Fabuła HD', 'wiki_page': None},
{'epg_id': '14130', 'index': '30', 'name': 'TVP Seriale', 'wiki_page': None},
{'epg_id': '14016', 'index': '31', 'name': 'TVP Kultura', 'wiki_page': None},
{'epg_id': '14237', 'index': '32', 'name': 'Stopklatka TV HD', 'wiki_page': None},
{'epg_id': '15014', 'index': '33', 'name': 'Kino Polska HD', 'wiki_page': None},
{'epg_id': '14132', 'index': '34', 'name': 'Kino TV HD', 'wiki_page': None},
{'epg_id': '14176', 'index': '35', 'name': 'TVN Style HD', 'wiki_page': None},
{'epg_id': '14072', 'index': '36', 'name': 'TLC HD', 'wiki_page': None},
{'epg_id': '15021', 'index': '37', 'name': 'HGTV Home & Garden HD', 'wiki_page': None},
{'epg_id': '14293', 'index': '38', 'name': 'Food Network HD', 'wiki_page': None},
{'epg_id': '14134', 'index': '39', 'name': 'TVP Historia', 'wiki_page': None},
{'epg_id': '14240', 'index': '40', 'name': 'Fokus TV HD', 'wiki_page': None},
{'epg_id': '14212', 'index': '41', 'name': 'Planete+ HD', 'wiki_page': None},
{'epg_id': '14178', 'index': '42', 'name': 'TVN Turbo HD', 'wiki_page': None},
{'epg_id': '14155', 'index': '43', 'name': 'Discovery Channel HD', 'wiki_page': None},
{'epg_id': '14156', 'index': '44', 'name': 'National Geographic HD', 'wiki_page': None},
{'epg_id': '14242', 'index': '45', 'name': 'TVP ABC', 'wiki_page': None},
{'epg_id': '14208', 'index': '46', 'name': 'MiniMini+ HD', 'wiki_page': None},
{'epg_id': '14123', 'index': '47', 'name': 'Disney Junior', 'wiki_page': None},
{'epg_id': '14187', 'index': '48', 'name': 'Nick Jr.', 'wiki_page': None},
{'epg_id': '14117', 'index': '49', 'name': 'Nickelodeon', 'wiki_page': None},
{'epg_id': '15044', 'index': '50', 'name': 'Disney Channel HD', 'wiki_page': None},
{'epg_id': '15031', 'index': '51', 'name': 'Disney XD', 'wiki_page': None},
{'epg_id': '14217', 'index': '52', 'name': 'Cartoon Network HD', 'wiki_page': None},
{'epg_id': '14003', 'index': '53', 'name': 'Tele 5', 'wiki_page': None},
{'epg_id': '14007', 'index': '54', 'name': 'TVS', 'wiki_page': None}

]

